### ISSUE TITLE
App does not work

### ISSUE THREAD

**Issue by alikhil** [kos33rd/rickandmorty-app#1]
I have just cloned the repo, installed dependencies, run `npm run dev:api` and when I opened the app in browser there is only white screen and `TypeError: b is undefined redux.js:573` error in the console

**Comment by kos33rd** [comment]
Hi!
Thanks for the report.

I tried to reproduce the bug on my own PC and Mac with clean install, but with no luck.
Could you please provide some additional information about your environment?

* Node JS and NPM versions
* OS
* Additional environment variables (such as PORT)
* Browser

**Comment by alikhil** [comment]
Yes, of course

MacOS Sierra 10.12.6 (16G1918)
Browser: Firefox Quantum 67.0.1 (64-bit)
node: v8.4.0
npm: v6.9.0

**Comment by kos33rd** [comment]
@alikhil thanks.

Indeed, there was a problem with redux middleware composition when no redux dev tools browser plugin being installed. 

Fixed this issue in 1f386994e7f63449eca9f7808882ffa642b527df. Could you recheck, please?

**Comment by alikhil** [comment]
Yes, it works now! Thank you!
